"""Add dollar_type_id foreign key to usd_to_ars

Revision ID: 6b1a18870714
Revises: f2f41212719b
Create Date: 2025-03-19 21:05:49.567079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1a18870714'
down_revision = 'f2f41212719b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usd_to_ars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dollar_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'dollar_type', ['dollar_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usd_to_ars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dollar_type_id')

    # ### end Alembic commands ###
